adobe/aquarium-fish

- go.mod
- go.sum
- lib/drivers/aws/aws.go
- lib/drivers/aws/definition.go
This change fixes an issue with waiting for instance disks/ip and adds a feature to specify key id or alias for the newly created disks.
fixes: #3 
Manually
> AWS: Fixed a couple of issues and added encryption key for new disks

- lib/drivers/aws/aws.go
- lib/drivers/docker/docker.go
- lib/drivers/driver.go
- lib/drivers/vmx/vmx.go
- lib/fish/application.go
- lib/openapi/api/api_v1.go
Found that it's actually dangerous to not filter AMI and snapshots by completion - in case snapshot was just taken it will be the first in the list, but still pending so all the requests for the resource uses such snapshot will fail until it will be prepared.
Also added the way to tell the snapshot api user some info about the taken snapshots - just in case he would like to find them later.
fixes: #3 
Manually
> AWS: Added filters to use only completed snaps & ami's and info return to snapshot

- _build.sh
- go.mod
- go.sum
- lib/fish/application.go
- lib/fish/label.go
- lib/fish/location.go
- lib/fish/node.go
- lib/fish/resource.go
- lib/fish/servicemapping.go
- lib/fish/user.go
- lib/fish/vote.go
- lib/openapi/api/api_v1.go
- lib/openapi/openapi.go
- lib/util/expression_sql_filter.go
- lib/util/expression_sql_filter_test.go
- lib/util/file_replace_token_test.go
- tests/label_find_filter_sql_injection_test.go
This security fix closes the hole in API during get requests that tries to find items in DB using user-provided SQL-queries. The fix uses SQL parser to cut out the expression and not to allow any other statements to get through. So the interface was not changed and just improved from security perspective.
In addition it removes version duplication in code generation (openapi) & uses cached oapi-codegen binary to allow to separate dependency loading & build and improve speed of code gen.
fixes: #33 
Automatically through unit and integration tests
> Fixed API security issue with potential SQL injection in filter

- .github/workflows/main.yml
- README.md
- docs/openapi.yaml
- lib/drivers/aws/driver.go
- lib/drivers/aws/tasks.go
- lib/drivers/aws/util.go
- lib/drivers/docker/driver.go
- lib/drivers/docker/util.go
- lib/drivers/driver.go
- lib/drivers/task.go
- lib/drivers/test/config.go
- lib/drivers/test/definition.go
- lib/drivers/test/driver.go
- lib/drivers/test/tasks.go
- lib/drivers/vmx/driver.go
- lib/drivers/vmx/util.go
- lib/fish/application.go
- lib/fish/application_state.go
- lib/fish/application_task.go
- lib/fish/fish.go
- lib/fish/resource.go
- lib/fish/user.go
- lib/openapi/api/api_v1.go
- tests/application_task_notexisting_fail_test.go
- tests/application_task_snapshot_by_user_test.go
- tests/cant_allocate_too_big_label_test.go
- tests/generated_uids_prefix_is_node_prefix_test.go
- tests/simple_app_create_destroy_test.go
- tests/three_apps_with_limit_test.go
- tests/two_apps_with_limit_test.go
The change is quite big due to alot of design flaws was rethought. In general it adds ApplicationTask struct, but also seriously changed the driver & resource structs & interfaces.
* Added when field to ApplicationTask to specify when to execute task - especially useful for `snapshot` to execute before DEALLOCATE
* Moved ApplicationStatus aside to use in ApplicationTask `when` field
* Redesigned Resource to put identifier field in it in order to use hwaddr only by it's direct purpose.
* The driver Allocate/Status/Deallocate interfaces was moved to direct use of Resource instead of basic types - I think it's much more convenient, because we would not need to change interfaces much and they will be much more stable in time. Drivers would be able to use struct fields and if we adding a new …
> Reimplemented snapshot mechanims & redesigned drivers & resource interfaces

- docs/openapi.yaml
- lib/fish/config.go
- lib/fish/fish.go
- lib/fish/label.go
- tests/label_lifetime_timeout_test.go
With lifetime timeout we can be sure the application resource will not be executed forever if something bad happened and based on this timeout fish node will be able to do some heuristics on how much time left till provisioning the next resource (#38).
The duration is set in standard golang format as string "1h2m3s", if it's empty or 0 - the default from fish config will be used. And if it's negative (like "-1s") then the resource should exist until user say so by deallocating it.
This change really helps with clouds where we certainly don't need to left the resources for long time.
fixes: #28 
Automatically
> Added lifetime for the Resources in Label definition

- examples/create_user.sh
- lib/fish/fish.go
- tests/default_lifetime_timeout_test.go
- tests/label_overrides_default_lifetime_timeout_test.go
A small fix for not properly working lifetime in fish node configuration - also added a couple of tests to ensure it will work properly & label lifetime will override the default one.
Caused by: #39 
Automatically
> Fixed an issue with default lifetime & added some tests for that

- lib/drivers/aws/config.go
- lib/drivers/aws/driver.go
- lib/drivers/vmx/driver.go
- lib/drivers/vmx/util.go
- lib/fish/drivers.go
- lib/util/download_unpack_archive.go
Now images and VMX Allocation cleans up if something bad happened during the process. And this change also contains a number of bugfixes for AWS driver.
* Cleanup is quite an important feature, otherwise automated Fish is clogging the disk or leftovers from the bad allocations. Also it's good to clean if images was not downloaded/unpacked correctly (I'm looking at you, max opened files on mac!)
* Removing driver from the list if it failed preparation phase - if they are not prepared, so what's the point of having them in the roster...
* 1 minute retry AWS connection on start in case network is not working - caught on mac after reboot, service starts and gets no internet...
* Fixed nasty issue with waiting of AWS instance IP and disks - it sometimes don't get the IP immediately and just …
> Solved issue with cleanup after fail and a number of bugfixes for AWS

- lib/drivers/test/config.go
- lib/drivers/test/driver.go
- lib/drivers/test/tasks.go
- lib/drivers/vmx/driver.go
- lib/fish/fish.go
- tests/allocate_multidefinition_label_test.go
- tests/application_task_notexisting_fail_test.go
- tests/application_task_snapshot_by_user_test.go
- tests/cant_allocate_too_big_label_test.go
- tests/default_lifetime_timeout_test.go
- tests/generated_uids_prefix_is_node_prefix_test.go
- tests/helpers.go
- tests/label_find_filter_sql_injection_test.go
- tests/label_lifetime_timeout_test.go
- tests/label_overrides_default_lifetime_timeout_test.go
- tests/simple_app_create_destroy_test.go
- tests/three_apps_with_limit_fish_restart_test.go
- tests/three_apps_with_limit_test.go
* BUGFIX: The changes about node resources monitoring and drivers placement messed up the node restart procedure if there was allocated resources, so fixed it and added integration test to fight the potential regression.
* BUGFIX: Fixed the issue with not stopping VMX VM's if they don't want to do that through soft procedure.
caused by: #37
Automatically
> BUGFIX: Allocated restart and VMX hard stop

- build.sh
- lib/drivers/aws/driver.go
Fixed a small issue during running an actual mac machine using AWS provider.
Also btw fixed sed command during the build on mac, because was incompatible with bsd sed.
None
Manual - allocate/destroy of the mac2.metal type instance
> Fixed issue with running mac nodes on AWS

- build.sh
Not important small fix, because `dash` doesn't really like jobs -r. Also if we will use only `-p` - it will display the same pid's even when they are completed.
None
Fun for sure
Manually
> In dash interp `jobs -r` is not supported, so cutting it off

- go.mod
> Before Go 1.21, the initial release of a Go toolchain was
> version 1.N, not 1.N.0, so for N < 21, the ordering is
> adjusted to place 1.N after the release candidates.
>
> https://go.dev/doc/toolchain#version
Go changed its versioning scheme in 1.21 from `<major>.<minor>` to `<major>.<minor>.<patch>`.  CodeQL analysis flags this stating the lack of a patch number "may cause some `go` commands to fail."
CodeQL Analysis warns that some tooling may break without the patch number.
It has not been; other than CI.
> Add patch version number in go.mod (X.Y => X.Y.Z)

- CODEOWNERS
- README.md
- docs/openapi.yaml
- lib/openapi/api/api_v1.go
Integrated pprof to get profiling of the running Fish node - really helpful to understand what's inside causing bugs.
Tried to implement through `pperf.Index()`, but it's processing only handlers without the advanced calls like trace & profile... So implementation is a bit bigger then could be...
#64 
In order to debug OOM's
Manually
> Added pprof into the node API to debug memory leaks

- lib/drivers/aws/config.go
- lib/drivers/aws/driver.go
- lib/drivers/aws/task_image.go
- lib/drivers/aws/task_snapshot.go
- lib/drivers/aws/util.go
- lib/fish/fish.go
Found TaskImage for windows images generates successful output even for timeout on image availability waiting - so fixed that and added much more logging to easily figure out what's happening and where.
#74
It should be just better
Manually
> Fix for hardcoded image wait timeout on TaskImage

- .github/workflows/main.yml
Incorrect token usage in workflow prevented to publish.
CI should work properly
Automatic
> Fixed issue with publish benchmark results to gh-pages

- docs/openapi.yaml
- lib/openapi/api/api_v1.go
The change allows admin and user himself to change password when needed. Admin can change the other users passwords and user can change it's own password now. Before admin was able to recreate user, but for admin there was no way to change auto-generated password.
Needed for smooth migration
Manually
> Allow user to change its password

- .github/workflows/main.yml
- docs/drivers/aws/aws_simulator/aws_dedicated_mac_pool_simulator.py
- lib/drivers/aws/config.go
- lib/drivers/aws/dedicated_pool.go
- lib/proxyssh/proxy.go
Figured that dedicated host is attached to zone and can't be moved across, so in case we consumed all the dedicated hosts of type in specific zone - we need to switch to another one. So for now the logic is sequential, but maybe in the future will be needed to add different distribution policies to balance between the zones (will be complicated, because AWS gives no interfaces to check how much hosts left in the zone).
**WARNING:** Changes interface for dedicated hosts configuration: `zone` replaced with `zones`, which contain list of strings.
#60 
Ya know, for fun! (and actually needed to make our pool work correctly of course)
Manually
> AF-60 Support multiple zones for dedicated hosts

- lib/drivers/aws/dedicated_pool.go
- lib/drivers/aws/driver.go
- lib/drivers/aws/util.go
- tests/perf_allocate_apps_stress_test.go
- tests/perf_max_requests_test.go
Bugfix: Figured it's not enough to just locate the dedicated host in the pool - we need to ensure that subnet is picked up correctly for the instance. Otherwise we seeing how instances are failed to be allocated because of mismatch of the picked instance subnet and dedicated host zone.
#60 
All bugs need to be out
Manually
> AF-60 Fixed missed instance zone filtering when using dedicated pool

- docs/openapi.yaml
- lib/drivers/aws/config.go
- lib/drivers/aws/dedicated_pool.go
- lib/drivers/aws/driver.go
- lib/fish/config.go
- lib/fish/fish.go
- lib/openapi/types/resources.go
- lib/util/duration.go
- lib/util/duration_test.go
- tests/apps_with_resources_limit_test.go
Those improvements needed to give fish node more flexibility in managing the workload.
1. Global slots for the node to limit local apps per node
2. Warning about driver's AvailableCapacity long exec
3. ReleaseDelay to control for how long we need to keep dedicated hosts
4. PendingToAvailableDelay dedicated host param to hotfix AWS API
5. Duration now can be set to days, weeks, months and years
#96 
Better supportability
Manually & automatically
> AF-96 A bunch of small improvements

- lib/drivers/aws/dedicated_pool.go
- lib/drivers/aws/driver.go
- lib/fish/fish.go
- tests/cleanupdb_fish_restart_test.go
- tests/helper/fish.go
- tests/three_apps_with_limit_fish_restart_test.go
The issue with long allocating apps could be solved 2 ways: decrease the allocation time or moving towards better handling the apps in-between the election rounds. Need to think more about the latter, but we already can cache the availability for AWS to not spend hundreds of milliseconds to get the same data from AWS.
#98 
Manually
> AF-98 Added cache to AWS availability and new test to check restart app cleanup

- .github/workflows/main.yml
- lib/database/application.go
- lib/database/application_state.go
- lib/database/application_task.go
- lib/database/database.go
- lib/database/db.go
- lib/drivers/provider/aws/dedicated_pool.go
- lib/fish/config.go
- lib/fish/election.go
- lib/fish/execute.go
- lib/fish/fish.go
- lib/fish/vote.go
- tests/app_election_recovery_after_failed_allocation_test.go
- tests/cleanupdb_check_test.go
- tests/cleanupdb_fish_restart_test.go
- tests/default_lifetime_timeout_test.go
- tests/label_lifetime_timeout_test.go
- tests/label_overrides_default_lifetime_timeout_test.go
- tests/long_allocating_app_test.go
- tests/maintenance_mode_test.go
- tests/perf_allocate_apps_stress_test.go
- tests/perf_jenkins_agents_awaiting_test.go
- tests/perf_jenkins_agents_check_pickups_test.go
- tests/perf_max_requests_test.go
- tests/simple_app_create_destroy_test.go
Switching interval-based polling of Application processes to event-based ones to speedup the passthrough.
Now it's processing the incoming applications through the election & allocation passes very fast and not collecting them in batches that in worst case could lead to ~10sec delay. Also election process now has recovery mechanisms in case node went down during allocation - so the cluster could recover the Application and retry with another node.
#94 
In order to be able to handle much more workload
Automatically
> AF-94 Reorganizing internal processing to be more responsive & improve workload processing

- lib/database/application.go
- lib/database/application_resource.go
- lib/database/application_resource_access.go
- lib/database/application_state.go
- lib/database/application_task.go
- lib/database/database.go
- lib/database/label.go
- lib/database/node.go
- lib/database/raw.go
- lib/database/servicemapping.go
- lib/database/user.go
- lib/drivers/drivers.go
- lib/fish/config.go
- lib/fish/election.go
- lib/fish/execute.go
- lib/fish/fish.go
- tests/compactdb_check_test.go
Change was made based on extensive / stress testing of the fish node, which helped to identify:
* Issue with bitcask on executing Merge operation - it was not designed to be executed in parallel with the regular DB operations and leaded to issues with requests as well as corruption of the database on disk and in memory: https://git.mills.io/prologic/bitcask/issues/276 - when it will be solved we can remove the mutex. Workaround implements simple RW mutex to separate CompactDB operation with regular DB utilization tasks. Special test was added to ensure it's working correctly.
* Channels send operations was moved to goroutines to not block the application background process and init phase.
* Previously was missed RECALLED status now also a part of cleanup procedures, so recalled apps now …
> AF-94 Workaround for Merge of bitcask & multiple other fixes for processes

- lib/drivers/provider/vmx/util.go
- lib/fish/execute.go
- tests/compactdb_check_test.go
- tests/helper/fish.go
Two changes here:
* After a night of testing I found the app timeout is not working correctly - it's just creating the state not checking if the app exists, so bloating the database. Added a quick fix for that and now removing app timeout on deallocation. Updated compactdb test to check this behavior as well. Also found deadlock with channels there - oh those channels...
* Also today we found that git >=2.35 don't really like to be running on windows with wrong owner for the workspace, so I've added VMX driver ability to create raw disks instead of formatting them on the host system to the limited amount of filesystems. That was a relatively legacy feature, so with modern bait images containing diskmount role (which is formatting the attached raw disks) we don't need to strictly rely on …
> AF-94 Fixed issue with leftover app timeouts and btw added VMX raw disk

- lib/drivers/gate/proxyssh/config.go
- lib/drivers/provider/aws/config.go
- lib/drivers/provider/aws/driver.go
- lib/drivers/provider/aws/options.go
- lib/openapi/api/api_v1.go
Change allows to use ProxySSH gate with AWS provider driver.
* Changed default port 1222 for the ProxySSH - old one was 1022, which is in restricted system ports.
* Added ability to generate keypairs if instance_key is set to "generate" Authentication is set for the label - otherwise not spending time on that.
* Added security_groups to be able to specify multiple groups when needed - that makes management of similar firewalls easier.
* Passing Authentication to the Resource
* Modified tags logic to have it common between keys & instances.
#61 
Need to be done
Manually
> AF-61 Connected AWS to ProxySSH

- build.sh
- lib/drivers/gate/proxyssh/proxy.go
- lib/drivers/provider/aws/task_snapshot.go
- test_docker.sh
- tests/helper/ssh.go
Fixes the issue with broken snapshot as a result of the task. The consistence is more important then no matter what prepare a snapshot, especially if it's a broken one.
Also partially fixed issue with openssh - now test tty client waits a second for shell response before beginning input - that solves some issues with too early input, but not all of them - for example it seems proxy closes the channel too soon and don't receive "exit", but that's an issue for future me.
Fixes: #113 
Bug must be exterminated
Manually
> AF-113 Increased AWS stop timeout to 30 mins and made snapshot fail if instance is not stopped

- lib/drivers/gate/proxyssh/proxy.go
- lib/drivers/provider/aws/driver.go
- tests/proxyssh_key_test.go
Fixed 2 bugs:
* AWS: Proper cleanup of the instance generated keys - previously used instance id instead of name.
* Fixed issue with ProxySSH reverse port forwarding - now it works just fine.
#61 
Debugging is closer and closer!
Manually & Automatically
> AF-61 Fixed issues with reverse proxy handling and AWS generated keys cleanup
